services:
  api:
    build: .
    container_name: auth_api
    ports:
      - "1024:1024"
      - "1025:1025"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    restart: always
    user: root