from .appearance_setting import AppearanceSetting
from .category import Category
from .course import Course
from .discount import Discount
from .duration_range import DurationRange
from .enrollment import Enrollment
from .faq import FAQ
from .feedback import Feedback
from .help import Help
from .lesson import Lesson
from .notification_setting import NotificationSetting
from .notification import Notification
from .price_range import PriceRange
from .privacy_policy import PrivacyPolicy
from .promotion import Promotion
from .security_setting import SecuritySetting
from .setting import Setting
from .settings_menu import SettingsMenu
from .student_lesson import StudentLesson
from .tag import Tag
from .terms_and_conditions import TermsAndConditions
from .wishlist import Wishlist
from .student import Student